require 'rails_helper'

RSpec.describe Chf::Export::GenericFileConverter do
  let!(:file) { FactoryGirl.create :generic_file, :with_complete_metadata, :with_system_metadata }
  let(:json) { "{\"id\":\"#{file.id}\",\"label\":\"labellabel\",\"depositor\":\"depositor@example.com\",\"relative_path\":\"relpathrelpath\",\"import_url\":\"importurlimporturl\",\"resource_type\":[\"resource_typeresource_type\"],\"title\":[\"titletitle\"],\"creator\":[\"creatorcreator\"],\"contributor\":[\"contributorcontributor\"],\"description\":[\"descriptiondescription\"],\"rights\":[\"rightslicense\"],\"publisher\":[\"publisherpublisher\"],\"date_created\":[\"date_createddate_created\"],\"date_uploaded\":\"2016-06-21T09:08:00.000+00:00\",\"date_modified\":\"2016-06-21T09:08:00.000+00:00\",\"subject\":[\"subjectsubject\"],\"language\":[\"languagelanguage\"],\"identifier\":[\"external_id\"],\"based_near\":[\"based_nearbased_near\"],\"related_url\":[\"http://example.org/TheRelatedURLLink/\"],\"bibliographic_citation\":[\"bibliographic_citationbibliographic_citation\"],\"source\":[\"sourcesource\"],\"visibility\":\"restricted\",\"versions\":[],\"permissions\":[{\"id\":\"#{file.permissions.first.id}\",\"agent\":\"http://projecthydra.org/ns/auth/person#depositor@example.com\",\"mode\":\"http://www.w3.org/ns/auth/acl#Write\",\"access_to\":\"#{file.id}\"}],\"artist\":[\"artistartist\"],\"author\":[\"authorauthor\"],\"addressee\":[\"addresseeaddressee\"],\"creator_of_work\":[\"creator_of_workcreator_of_work\"],\"engraver\":[\"engraverengraver\"],\"interviewee\":[\"intervieweeinterviewee\"],\"interviewer\":[\"interviewerinterviewer\"],\"manufacturer\":[\"manufacturermanufacturer\"],\"photographer\":[\"photographerphotographer\"],\"printer_of_plates\":[\"printerprinter\"],\"place_of_interview\":[\"place_of_interviewplace_of_interview\"],\"place_of_manufacture\":[\"place_of_manufactureplace_of_manufacture\"],\"place_of_publication\":[\"place_of_publicationplace_of_publication\"],\"place_of_creation\":[\"place_of_creationplace_of_creation\"],\"admin_note\":[\"admin_noteadmin_note\"],\"credit_line\":[\"Courtesy of CHF\"],\"division\":\"divisiondivision\",\"file_creator\":\"file_creatorfile_creator\",\"genre_string\":[\"genre_stringgenre_string\"],\"extent\":[\"extentextent\"],\"medium\":[\"mediummedium\"],\"physical_container\":\"physical_containerphysical_container\",\"rights_holder\":\"rights_holderrights_holder\",\"series_arrangement\":[\"seriesseries\"],\"date_of_work\":[{\"id\":\"#{file.date_of_work.first.id}\",\"start\":\"1920\",\"finish\":\"1929\",\"start_qualifier\":\"circa\",\"finish_qualifier\":\"before\",\"note\":\"The twenties\"}],\"inscription\":[{\"id\":\"#{file.inscription.first.id}\",\"location\":\"inscriptionlocation\",\"text\":\"inscriptiontext\"}],\"additional_credit\":[{\"id\":\"#{file.additional_credit.first.id}\",\"role\":\"photographer\",\"name\":\"Puffins\",\"label\":\"Photographed by Puffins\"}]}" }

  describe "to_json" do
    subject { described_class.new(file) }
    it do
      expect(subject.to_json).to eq json
    end

  end
end
